Repository rss-bug-busters/eCommerce-Application, pull requests merged in 2024-06, with the labels that each got.

#75 Docs/Correct Technology Stack
  README.md
Labels: documentation

#76 Feat/Header enhancements
  src/assets/svg/cross.svg
  src/assets/svg/menu.svg
  src/components/Header/Header.tsx
  src/components/Header/UserDropdown/UserDropdown.tsx
  src/pages/CatalogPage/index.tsx
  src/tailwindcss.css
Labels: enhancement

#78 Make only src files visible in test coverage
  src/tests/setup.ts
  vite.config.ts
Labels: bug
